name = "ruby"
variable_format = "snake_case"
source_file_ext = "rb"
allow_uppercase_vars = false
keywords = [
  "__ENCODING__", "__LINE__", "__FILE__", "BEGIN", "END", "alias", "and", "begin", "break", "case",
  "class", "def", "defined", "do", "else", "elsif", "end", "ensure", "false", "for",
  "if", "in", "module", "next", "nil", "not", "or", "redo", "rescue", "retry", "return",
  "self", "super", "then", "true", "undef", "unless", "until", "when", "while", "yield"
]
aliases = ["rb"]

[type_tokens]
Int = "to_i"
Long = "to_i"
Float = "to_f"
Bool = "to_bool"

