name = "c"
variable_format = "snake_case"
source_file_ext = "c"
allow_uppercase_vars = false
# TODO
keywords = [
  "for" 
]

[type_tokens]
Int = "int"
Long = "long long"
Float = "float"
Bool = "int"
String = "char"
Word = "char"