name = "rust"
variable_format = "snake_case"
source_file_ext = "rs"
allow_uppercase_vars = false
keywords = [
  "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let",
  "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true",
  "type", "unsafe", "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro", "override",
  "priv", "typeof", "unsized", "virtual", "yield", "try", "macro_rules", "union", "'static"
]

[type_tokens]
Int = "i32"
Long = "i64"
Float = "f64"
Bool = "to_bool"

